version: '3.7'

services:
  k3s_server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
      - K3S_TOKEN=${K3S_TOKEN:-vald}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - .:/output
    ports:
      - 6443:6443
      - 80:80
      - 443:443
    healthcheck:
      test: [ "CMD-SHELL", "kubectl get --raw='/readyz'" ]
      interval: 1s
      timeout: 1s
      retries: 5
  k3s_agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: agent
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    environment:
      - K3S_URL=https://server:6443
      - K3S_TOKEN=${K3S_TOKEN:-vald}
    ports:
      - 30081:8081
      - 30001:3001
